name: cash-app
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_APP_NAME: ${VITE_APP_NAME:-}
                VITE_API_BASE_URL: ${VITE_API_BASE_URL:-}
        image: zcodein/cash-frontend-app:1.0
        container_name: cash-frontend-app
        ports:
            - '3000:80'
        restart: unless-stopped
